### ISSUE TITLE
juju-lint breaks on running relation checks on Juju 3.4

### ISSUE THREAD

**Issue by Vultaire** [canonical/juju-lint#286]
During a recent cloud handover, I found this issue blocking automatic review of relations on one of the models.

The error looks like this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/usr/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/ubuntu/juju-lint/shim.py", line 5, in <module>
    main()
  File "/home/ubuntu/juju-lint/jujulint/cli.py", line 241, in main
    cli.audit_file(cli.manual_file, cloud_type=cli.cloud_type)
  File "/home/ubuntu/juju-lint/jujulint/cli.py", line 157, in audit_file
    linter.lint_yaml_file(filename)
  File "/home/ubuntu/juju-lint/jujulint/lint.py", line 1396, in lint_yaml_file
    return self.do_lint(parsed_yaml)
  File "/home/ubuntu/juju-lint/jujulint/lint.py", line 1425, in do_lint
    self.check_relations(input_file)
  File "/home/ubuntu/juju-lint/jujulint/lint.py", line 763, in check_relations
    ).check()
  File "/home/ubuntu/juju-lint/jujulint/checks/relations.py", line 258, in check
    rule.check()
  File "/home/ubuntu/juju-lint/jujulint/checks/relations.py", line 147, in check
    self.relation_exist_check()
  File "/home/ubuntu/juju-lint/jujulint/checks/relations.py", line 163, in relation_exist_check
    apps_related_with_relation_rule = self.input_file.filter_by_relation(
  File "/home/ubuntu/juju-lint/jujulint/model_input.py", line 247, in filter_by_relation
    apps_related.update(relations.get(endpoint, []))
TypeError: unhashable type: 'dict'
```

It seems that Juju has changed the format of its relation data in "juju status --format=yaml".  Instead of remote apps being listed as simple strings (which would have worked with the above code), they are now dictionaries.  Concrete exmaple: ```{'interface': 'nrpe-external-master', 'related-application': 'ceph-mon', 'scope': 'container'}```

Here is an example fragment from "juju status --format=yaml" which could be stitched into a test YAML to reproduce the issue:

```
  ubuntu-advantage:
    charm: ubuntu-advantage
    base:
      name: ubuntu
      channel: "22.04"
    charm-origin: charmhub
    charm-name: ubuntu-advantage
    charm-rev: 79
    charm-channel: latest/stable
    exposed: false
    application-status:
      current: active
      message: Attached (esm-infra,livepatch)
      since: 26 Apr 2024 20:47:16Z
    relations:
      juju-info:
      - related-application: ceph-dashboard-loadbalancer
        interface: juju-info
        scope: container
      - related-application: ceph-fs
        interface: juju-info
        scope: container
      - related-application: ceph-mon
        interface: juju-info
        scope: container
      - related-application: ceph-osd
        interface: juju-info
        scope: container
      - related-application: ceph-radosgw
        interface: juju-info
        scope: container
      - related-application: cos-proxy
        interface: juju-info
        scope: container
    subordinate-to:
    - ceph-dashboard-loadbalancer
    - ceph-fs
    - ceph-mon
    - ceph-osd
    - ceph-radosgw
    - cos-proxy
    endpoint-bindings:
      "": oam-space
      juju-info: oam-space
```

juju-lint revision: 3a4b30a2370b0197613fe25ae8d9da39ff225fa9 (Tue Apr 30 15:01:11 2024 +0200)
Juju controller version: 3.4

**Comment by samuelallan72** [comment]
@Vultaire I'm trying to figure out how to reproduce this.  Would you have a more complete reproducer you can share?  Thanks.

**Comment by samuelallan72** [comment]
@Vultaire a fix has been merged and published to latest/edge.  Please try it out and let us know if there are still issues :)
