### ISSUE TITLE
version 1.0.7 is broken w/ error No module named 'invoke.vendor.decorator'

### ISSUE THREAD

**Issue by zxhdaze** [canonical/juju-lint#29]
After installing juju-lint from edge channel I hit following error in any command:
```bash
x1:➜  juju-lint git:(master) ✗ juju-lint 
Traceback (most recent call last):
  File "/snap/juju-lint/current/lib/python3.8/site-packages/fabric2/connection.py", line 7, in <module>
    from invoke.vendor.decorator import decorator
ModuleNotFoundError: No module named 'invoke.vendor.decorator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/juju-lint/100/bin/juju-lint", line 5, in <module>
    from jujulint.cli import main
  File "/home/rgildein/code/canonical/juju-lint/jujulint/cli.py", line 32, in <module>
    from jujulint.openstack import OpenStack
  File "/home/rgildein/code/canonical/juju-lint/jujulint/openstack.py", line 41, in <module>
    from jujulint.cloud import Cloud
  File "/home/rgildein/code/canonical/juju-lint/jujulint/cloud.py", line 40, in <module>
    from fabric2 import Config, Connection
  File "/snap/juju-lint/current/lib/python3.8/site-packages/fabric2/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/snap/juju-lint/current/lib/python3.8/site-packages/fabric2/connection.py", line 9, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'                                  [0.36s]
```

Snap info:
```bash
x1:➜  juju-lint git:(master) ✗ snap info juju-lint
name:      juju-lint
summary:   Linter for Juju models to compare deployments with configurable policy
publisher: Canonical✓
store-url: https://snapcraft.io/juju-lint
contact:   <email address hidden>
license:   unset
description: |
  Linter for remote or local Juju models.
  Compares remote deployments with configurable policy rules.
  Linting can also be performed on a YAML file representing cloud state.
commands:
  - juju-lint
snap-id:      jvBdiBE3Yg8PF8Nx9gda1G4JJHjQIJF4
tracking:     latest/edge
refresh-date: today at 08:15 CEST
channels:
  latest/stable:    1.0.6 2023-02-14  (91) 47MB classic
  latest/candidate: 1.0.7 2023-05-04 (100) 47MB classic
  latest/beta:      ↑                           
  latest/edge:      1.0.7 2023-05-04 (100) 47MB classic
installed:          1.0.7            (100) 47MB classic                           [0.51s]
```

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2023-05-31T06:30:57Z
 * owner: [rgildein](https://launchpad.net/~rgildein)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/2021939)

**Comment by zxhdaze** [comment]
(by [mertkirpici](https://launchpad.net/~mertkirpici))
juju-lint snap package needs to be rebuilt and uploaded. This issue is resolved in the latest release of fabric2 package. See section 3.1.0 of the fabric2 changelog[0]. 

Quoting the important bit

...
[Bug] #2263: Explicitly add our dependency on decorator to setup.py instead of using Invoke’s old, now removed, vendored copy of same. This allows Fabric to happily use Invoke 2.1 and above. Thanks to Luke Robison, Nick Humrich, and others, for the reports.
...

The current version installed in the edge snap is 3.0.1. Taken from the latest buildlog[1]:
...
Successfully installed PyYAML-6.0 attrs-23.1.0 bcrypt-4.0.1 cffi-1.15.1 colorlog-6.7.0 confuse-2.0.1 cryptography-40.0.2 fabric2-3.0.1 invoke-2.1.1 paramiko-3.1.0 pycparser-2.21 pynacl-1.5.0 python-dateutil-2.8.2 six-1.16.0
...

[0] https://www.fabfile.org/changelog.html
[1] https://launchpadlibrarian.net/664575107/buildlog_snap_ubuntu_focal_amd64_juju-lint_BUILDING.txt.gz

**Comment by zxhdaze** [comment]
(by [rgildein](https://launchpad.net/~rgildein))
Thanks Mert, I tested it locally and that triggered re-build. Version 1.0.7 in snapcraft.io
was updated and it's working fine.

Closing this issue.
