### ISSUE TITLE
juju-lint is broken when rsyslog-forwarder-ha charm is present

### ISSUE THREAD

**Issue by zxhdaze** [canonical/juju-lint#67]
can't run juju-link when bundle has rsyslog-forwarder-ha subordianate charm

ubuntu@ps6-infra1:~/ps6/handover/juju-lint$ juju-lint -c /snap/juju-lint/current/contrib/openstack-focal-ovn.yaml -t openstack ./juju-status-openstack.json
2023-03-06 20:59:12 [INFO] juju-lint version 1.0.6 starting...
        * Config directory: /home/ubuntu/.config/juju-lint
        * Cloud type: openstack
        * Manual file: ./juju-status-openstack.json
        * Rules file: /snap/juju-lint/current/contrib/openstack-focal-ovn.yaml
        * Log level: INFO

2023-03-06 20:59:12 [WARNING] Regex autodetection feature of the eq operator is deprecated. It will only check for equality in the future. Please use the search operator for regex checks.
2023-03-06 20:59:12 [INFO] [./juju-status-openstack.json] Linting manual file...
Traceback (most recent call last):
  File "/snap/juju-lint/91/bin/juju-lint", line 8, in <module>
    sys.exit(main())
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/cli.py", line 212, in main
    cli.audit_file(cli.manual_file, cloud_type=cli.cloud_type)
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/cli.py", line 128, in audit_file
    linter.lint_yaml_file(filename)
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/lint.py", line 1367, in lint_yaml_file
    return self.do_lint(parsed_yaml)
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/lint.py", line 1394, in do_lint
    self.process_subordinates(parsed_yaml[applications][app], app)
  File "/snap/juju-lint/current/lib/python3.8/site-packages/jujulint/lint.py", line 190, in process_subordinates
    allow_multiple = self.lint_rules["subordinates"][charm].get(
KeyError: 'rsyslog-forwarder-ha'

juju-lint version:   1.0.7.dev16+g3313998

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2023-03-06T21:05:35Z
 * owner: [qch2012](https://launchpad.net/~qch2012)
 * assignee: [mertkirpici](https://launchpad.net/~mertkirpici)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/2009536)

**Comment by zxhdaze** [comment]
(by [qch2012](https://launchpad.net/~qch2012))

**Comment by zxhdaze** [comment]
(by [mertkirpici](https://launchpad.net/~mertkirpici))
A revision that includes the fix is released to the edge channel. Could you verify that the issue is resolved?
